// Generated by ReScript, PLEASE EDIT WITH CARE


var textEditor = document.getElementById("textEditor");

var textView = document.getElementById("textView");

var selectSmall = document.getElementById("selectSmall");

var selectRegular = document.getElementById("selectRegular");

var selectLarge = document.getElementById("selectLarge");

function updateTextView($$event) {
  textView.innerText = $$event.target.value;
  
}

function setFontSmall(param) {
  textView.classList.add("text-sm");
  return textView.classList.remove("text-2xl", "text-6xl");
}

function setFontRegular(param) {
  textView.classList.add("text-2xl");
  return textView.classList.remove("text-sm", "text-6xl");
}

function setFontLarge(param) {
  textView.classList.add("text-6xl");
  return textView.classList.remove("text-sm", "text-2xl");
}

textEditor.addEventListener("input", updateTextView);

textView.classList.add("text-2xl");

selectSmall.addEventListener("change", setFontSmall);

selectRegular.addEventListener("change", setFontRegular);

selectLarge.addEventListener("change", setFontLarge);

export {
  textEditor ,
  textView ,
  selectSmall ,
  selectRegular ,
  selectLarge ,
  updateTextView ,
  setFontSmall ,
  setFontRegular ,
  setFontLarge ,
  
}
/* textEditor Not a pure module */
